### ISSUE TITLE
Caffe Version

### ISSUE THREAD

**Issue by caseyanya** [Tyler-D/XNOR-Convolution-Operator#1]
Thanks for your work. 
I'm also interested in this topic, what version of XNOR did you use in this comparison? Can you give me some more details, thanks.

**Comment by Tyler-D** [comment]
Caffe is rc5 and the xnor is binarizing both weights and input. This is a raw version and I'm still working on it.

**Comment by caseyanya** [comment]
Thanks for your reply. 
Another question is, since there is no xnor operation in caffe, are you comparing with standard convolution in caffe?

By the way, did you try this before? 
https://github.com/HongxingGao/XNOR-Net

**Comment by Tyler-D** [comment]
@caseyanya  1) yes. 2) I tried that one and I found it is just a simulation of xnor-net using float gemm --- it can be slower than standard convolution in caffe because of  binarizing input and weights.
